vars: {
  d2-config: {
    layout-engine: elk
    # Terminal theme code
    theme-id: 100
  }
}

...@Style.d2

# Simple Objects

Object.com: {
	class: Comment
	label: General parameters
}

LuaExec {
	class: Task
	com {
		class: Comment
		label: Can run Lua code
	}
}
Object -> LuaExec

Event{
	class: Event
	com {
		class: Comment
		label: External will launch children 
	}
}
Object -> Event

Handler {
	class: Handler
	com {
		class: Comment
		label: Triggered when an event happens 
	}
}

LuaExec -> Handler

HandlersExecutor {
	class: [Handler ; Collection]
	com {
		class: Comment
		label: Can execute handlers
	}
}

Handler -> HandlersExecutor
Object -> HandlersExecutor

HandlersExecutor -> Event


LuaTask {
	class: Task
}
Handler -> LuaTask

MinMax {
	class: MinMax
}
Handler -> MinMax

NamedMinMax {
	class: MinMax
}
Handler -> NamedMinMax

MQTTTopic {
	class: Topic
}
Object -> MQTTTopic
Event -> MQTTTopic

Shutdown {
	class: Shutdown
}
LuaExec -> Shutdown


Timer {
	class: Timer
}
Event -> Timer
HandlersExecutor -> Timer

Tracker {
	class: Tracker
}
Handler -> Tracker
HandlersExecutor -> Tracker

pgsql : Database Add On {
	style.stroke-dash: 6

	mpgConnection {
		class: Database
	}

	pgSQL {
		class: Database
		style.fill: "linear-gradient(#888888, #f4a261)"
	}
	_.Object -> pgSQL
	mpgConnection -> pgSQL

	Feed {
		class: [Sql ; Lua]
	}
	mpgConnection -> Feed
	_.Handler -> Feed

	NamedFeed {
		class: [Sql ; Lua]
	}
	Feed -> NamedFeed

	AggregatedFeed {
		class: [Sql ; Lua]
	}
	Feed -> AggregatedFeed

	Purge {
		class: Sql
	}
	mpgConnection -> Purge
	_.Handler -> Purge

	Archiving {
		class: Sql
	}
	Purge -> Archiving
}

Toile: Toile Add On {
	style.stroke-dash: 6

	Renderer {
		class: [ TRenderer ; Lua ]

		DecorationsList {
			style.multiple: true
			class : TDecoration
		}

		PaintingsList {
			style.multiple: true
			class : TPainting
		}
	}
	_.LuaExec -> Renderer

	LCD {
		class: [ TLCD; Lua ]

		DecorationsList {
			style.multiple: true
			class : TDecoration
		}

		PaintingsList {
			style.multiple: true
			class : TPainting
		}
	}

	Renderer -> LCD {
		class: inherite
	}

	Decoration {
		class: [ TDecoration ; Lua ]
	}
	_.LuaExec -> Decoration 
	Decoration -> Renderer.DecorationsList
	Decoration -> LCD.DecorationsList

	Painting {
		class: TPainting
	}
	_.Object -> Painting
	Painting -> Renderer.PaintingsList
	Painting -> LCD.PaintingsList

	Field {
		class: [ TField ; Lua ]
		icon: https://icons.terrastruct.com/essentials/021-view.svg
	}
	_.Object -> Field
	_.Handler -> Field
	Painting -> Field
}

# Configuration

Config: { 
	TopicsList {
		class: Topic
	}

	EventsList {
		class: Event
	}

	TimersList {
		class: Timer
	}

	TrackersList {
		class: Tracker
	}

	MinMaxList {
		class: MinMax
	}

	NamedMinMaxList {
		class: MinMax
	}

	TasksList {
		class: Task
	}

	ShutdownsList {
		class: Shutdown
	}

	FeedsList {
		class: Sql
	}

	NamedFeedsList {
		class: Sql
	}

	AggregatedFeedsList {
		style.multiple: true
		class: Sql
	}

	pgSQLsList {
		class: Database
	}
}
Config.*.style.multiple: true
Config.*.style.stroke-width: 1

Event -> Config.EventsList
LuaTask -> Config.TasksList
MQTTTopic -> Config.TopicsList
Shutdown -> Config.ShutdownsList
Timer -> Config.TimersList
MinMax -> Config.MinMaxList
NamedMinMax -> Config.NamedMinMaxList
Tracker -> Config.TrackersList

pgsql.mpgConnection -> Config.pgSQLsList
pgsql.Feed -> Config.FeedsList
pgsql.NamedFeed -> Config.NamedFeedsList
pgsql.AggregatedFeed -> Config.AggregatedFeedsList

COnfig.*.style.stroke: black
