# Styles
# Make it easier to customize shapes

# Shapes

classes: {
	Comment: {
		style {
			fill: transparent
			italic: true
			stroke: transparent
		}
	}

	Task:{
		shape: step
		style.stroke: red
	}

	Event:{
		shape: diamond
		style.stroke-width: 6
		style.fill: aqua
	}

	Topic:{
		shape: document
		style.stroke-width: 6
		style.fill: lightsalmon
	}

	Timer:{
		shape: oval
		style.stroke-width: 6
		style.fill: gold
	}

	MinMax:{
		shape: hexagon
		style.stroke: red
	}

	Tracker:{
		shape: package
		style.stroke-width: 6
		style.fill: thistle
		style.stroke: red
	}

	Shutdown:{
		shape: step
		style.stroke: red
	}

	Handler:{
		shape: hexagon
	}

	Database:{
		shape: cylinder
	}

	Sql: {
		shape: queue
		style.fill: yellowgreen
	}

	Lua: {
		style.stroke: red
	}

	Collection: {
		style.multiple: true
	}

	inherite: {
		style {
			stroke: blue
			animated: true
		}
		target-arrowhead {
			shape: diamond
		}
	}

	TRenderer {
		icon: https://icons.terrastruct.com/essentials/144-television.svg
	}

	TLCD {
		icon: /usr/share/icons/elementary/mimes/64/text-spreadsheet.svg
	}

	TDecoration {
		icon: https://icons.terrastruct.com/essentials/004-picture.svg
	}

	TPainting {
		icon: https://icons.terrastruct.com/essentials/006-window.svg
	}

	TField {
		icon: https://icons.terrastruct.com/essentials/021-view.svg
	}

	TRenderer {
		icon: https://icons.terrastruct.com/essentials/144-television.svg
	}

	TDecoration {
		icon: https://icons.terrastruct.com/essentials/004-picture.svg
	}

	TPainting {
		icon: https://icons.terrastruct.com/essentials/006-window.svg
	}

	TField {
		icon: https://icons.terrastruct.com/essentials/021-view.svg
	}
}

# styles by function

classes {
	NoData {
		style.stroke: steelblue
		style.fill : lightblue
	}

	Data {
		style.stroke: coral
		style.fill: navajowhite
	}
}
