# Styles
# Make it easier to customize classes

classes: {
	Comment: {
		style {
			fill: transparent
			italic: true
			stroke: transparent
		}
	}

	Task:{
		shape: step
		style.stroke: red
	}

	Event:{
		shape: diamond
	}

	Topic:{
		shape: document
	}

	Timer:{
		shape: oval
	}

	MinMax:{
		shape: hexagon
		style.stroke: red
	}

	Tracker:{
		shape: package
		style.stroke: red
	}

	Shutdown:{
		shape: step
		style.stroke: red
	}

	Handler:{
		shape: hexagon
	}

	Database:{
		shape: cylinder
	}

	Sql: {
		shape: queue
		style.fill: yellowgreen
	}

	Collection: {
		style.multiple: true
	}

	Lua: {
		style.stroke: red
	}
}

