-- PostgreSQL database access definition
--
-- name of the timer
-- if not set, takes the filename
--->> name=toto
--
-- Connection string : see PostgreSQL documentation
-- Something like :
--	postgresql://[user[:password]@][[host][:port][,...]][/dbname][?name=value[&...]]
-->> pgConnectionstring=postgresql://test@torchwood.chez.moi
