classes: {
	Task:{
		shape: step
		style.stroke: red
	}

	Event:{
		shape: diamond
		style.stroke-width: 6
		style.fill: aqua
	}

	Topic:{
		shape: document
		style.stroke-width: 6
		style.fill: lightsalmon
	}

	Timer:{
		shape: oval
		style.stroke-width: 6
		style.fill: gold
	}

	MinMax:{
		shape: hexagon
		style.stroke: red
	}

	NamedMinMax:{
		shape: hexagon
		style.stroke: red
		border-radius: 5
	}

	Tracker:{
		shape: package
		style.stroke-width: 6
		style.fill: thistle
		style.stroke: red
	}

	Shutdown:{
		shape: step
		style.stroke: red
	}

	Handler:{
		shape: hexagon
	}

	Database:{
		shape: cylinder
	}

	Feed: {
		shape: queue
		style.fill: yellowgreen
	}

	NamedFeed: {
		shape: queue
		style.fill: yellowgreen
		border-radius: 5
	}

	Archiving: {
		shape: stored_data
		style.fill: yellowgreen
	}
}
